### ISSUE TITLE
PDF Ausdruck bzw. Anhang wird nicht mitgesendet

### ISSUE THREAD

**Issue by LukasBCG** [alyf-de/erpnext_datev#5]
Bei der ausgehenden E-Mail von DATEV wird der Ausdruck bzw. der Anhang nicht mitgesendet. Im Beispiel ist beides aktiviert und es ist ein normales Postfach hinterlegt. Die ankommende E-Mail hat keinen Anhang.

**DATEV-Einstellungen**
<img width="1621" alt="Bildschirmfoto 2023-01-27 um 15 27 07" src="https://user-images.githubusercontent.com/103038727/215111489-91f6ea9d-162a-4b1b-91e3-4458e07f25cd.png">

**DATEV-Einstellungen Detial**
<img width="694" alt="Bildschirmfoto 2023-01-27 um 15 28 10" src="https://user-images.githubusercontent.com/103038727/215111578-cb9bec65-2f70-4395-a36d-6c2e0ae5bd93.png">

**Doc-Type Ausgangsrechnung**
<img width="708" alt="Bildschirmfoto 2023-01-27 um 15 29 17" src="https://user-images.githubusercontent.com/103038727/215111672-d5daf2cf-4403-4548-a59e-61e25179a97b.png">

**E-Mail in Outlook**
<img width="972" alt="Bildschirmfoto 2023-01-27 um 15 28 36" src="https://user-images.githubusercontent.com/103038727/215111714-845b33d5-6ed5-476f-b6b9-cdf76d5929e1.png">

Verwendet wird ERPnext V14.
Ist das Problem bekannt?

**Comment by LukasBCG** [comment]
@barredterra Hey Raffael, kannst du etwas zu dem Problem sagen?
Danke! Viele Grüße Lukas

**Comment by barredterra** [comment]
@LukasBCG @saschnet kindly check if _Send Print as PDF_ is enabled in your **Print Settings**. If not, all prints attached to emails will be HTML instead of PDF. This is the same mechanism that is used when manually sending an email and selecting _Attach Document Print_.

https://docs.erpnext.com/docs/v12/user/manual/en/setting-up/print/print-settings#11-pdf-or-html

**Comment by LukasBCG** [comment]
<img width="2196" alt="Bildschirmfoto 2023-02-08 um 16 28 26" src="https://user-images.githubusercontent.com/103038727/217574695-a0606029-f4f5-4aea-a1b8-b120529ce504.png">
Das sind die Einstellungen unter **Druckeinstellungen**, wie sie auch zum Testzeitpunkt waren. Müsste passen, oder?

**Comment by barredterra** [comment]
Sieht gut aus – dann ist das ein anderes Problem. Zumindest in Version 13 ist der Anhang auf jeden Fall vorhanden, das habe ich gestern erst getestet. Version 14 müsste ich separat nochmal testen.

**Comment by saschnet** [comment]
Unsere Einstellungen sind genauso gesetzt wie bei LukasBCG. Wir nutzen ebenfalls Version 14 mit folgenden Versionen:
![grafik](https://user-images.githubusercontent.com/33368683/217663606-04127f2f-45f8-43e9-b3eb-0e84caf748df.png)

**Comment by LukasBCG** [comment]
> Unsere Einstellungen sind genauso gesetzt wie bei LukasBCG. Wir nutzen ebenfalls Version 14 mit folgenden Versionen: ![grafik](https://user-images.githubusercontent.com/33368683/217663606-04127f2f-45f8-43e9-b3eb-0e84caf748df.png)

Hi @saschnet, bei euch wird das/die PDFs er E-Mail auch nicht angehängt?
Das würde nahelegen, dass es ab V14 ein Problem gibt....

**Comment by saschnet** [comment]
Genauso ist es! Wir wollen nur die angehängten PDFs verschicken - diese werden aber nicht angehängt, wie oben von dir beschrieben.

**Comment by LukasBCG** [comment]
ok! @barredterra kannst du uns eine Einschätzung zu V14 geben und das Problem ggf. fixen?

**Comment by saschnet** [comment]
I am not experienced with erpnext/frappe and could not locate any obvious issues in the codebase.

@barredterra do you have any ideas?

**Comment by LukasBCG** [comment]
Ja, es wäre toll, wenn es hier Zeitnahe eine Lösung gäbe. Da wir dringend diese Funktion nutzen möchten. @barredterra

**Comment by barredterra** [comment]
https://www.gnu.org/philosophy/free-sw.html

Den Quellcode stellen wir kostenlos zur Verfügung, unsere Arbeitszeit jedoch nicht. Ich freue mich über Bug Reports, bitte aber darum, nur auf eine Lösung zu drängen, wenn ihr dafür auch eine Rechnung erhalten wollt.

**Comment by LukasBCG** [comment]
Kann ich gut nachvollziehen, kein Problem. Nehmt bis die Sache gefixt ist aber bitte den Hinweis auf Kompabilität zu V14 raus. Die ist in dem Fall nicht gegeben.

<img width="719" alt="Bildschirmfoto 2023-03-02 um 14 45 55" src="https://user-images.githubusercontent.com/103038727/222446401-4b6fdc0f-da39-4112-a371-29d79b49f48c.png">

**Comment by barredterra** [comment]
Das Problem sollte mit https://github.com/alyf-de/erpnext_datev/releases/tag/v14.0.2 behoben sein. Es kann allerdings noch ein paar Tage dauern, bis das Update auf Frappe Cloud verfügbar ist.
