### ISSUE TITLE
Anfangsbilanz wird nicht mit exportiert

### ISSUE THREAD

**Issue by tillmo** [alyf-de/erpnext_datev#7]
Unser Steuerberater hat darauf hingewiesen, dass in einem korrekten DATEV-Export die Anfangsbilanz eines Jahres mit enthalten sein muss, und zwar mit Gegenkonto 9000. Derzeit wird die Eröffnungsbilanz nicht mit exportiert, d.h. alle Konten fangen bei 0 an.

**Comment by barredterra** [comment]
Mit https://github.com/alyf-de/erpnext_datev/commit/a06f3ee809402eb40c9b866c67b6e878d8856780 (ab v14.0.3) kann das Gegenkonto für Eröffnungsbuchungen separat konfiguriert werden.
